# File autogenerated by hexa.run on {{date}}
FROM nginx:alpine

RUN echo -e "server {\n" \
          "  listen       80;\n" \
          "  server_name  localhost;\n" \
          "  location / {\n" \
          "      root   /usr/share/nginx/html;\n" \
          "      index  index.html index.htm;\n" \
          "  }\n" \
          "  error_page   500 502 503 504  /50x.html;\n" \
          "  location = /50x.html {\n" \
          "      root   /usr/share/nginx/html;\n" \
          "  }\n" \
          "  ssi on;\n" \
          "}\n" > /etc/nginx/conf.d/default.conf

RUN echo "<html><body><h1>Host: <!--#echo var=\"HOSTNAME\" --></h1>Hello Hexa</body></html>" > /usr/share/nginx/html/index.html

EXPOSE 80
