# File autogenerated by hexa.run on {{date}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: {{projectName}}
spec:
  selector:
    matchLabels:
      app: {{projectName}}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{projectName}}
    spec:
      containers:
      - name: {{projectName}}
        image: {{containerImage}}
        imagePullPolicy: Always
        resources:
         requests:
           cpu: 100m
           memory: 128Mi
         limits:
           cpu: 200m
           memory: 200Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: {{projectName}}
spec:
 type: LoadBalancer
 selector:
   app: {{projectName}}
 ports:
 - port: 80
   targetPort: 80


